apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: PostgreSQL
    access: proxy
    url: postgres:5432
    isDefault: true
    database: archestra
    user: archestra
    secureJsonData:
      password: archestra
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
