apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: shieldops
    user: shieldops
    secureJsonData:
      password: shieldops
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      postgresVersion: 1500
