apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true

  - name: PostgreSQL
    type: postgres
    uid: PostgreSQL
    access: proxy
    url: postgres:5432
    user: archestra
    isDefault: true
    editable: true
    jsonData:
      database: archestra
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
    secureJsonData:
      password: archestra
